# Retrieve the person with id=683915c05ab02e01c621272e
GET http://localhost:3001/api/persons/683915c05ab02e01c621272e

###
# What happens if a person with the id doesn't exist?
GET http://localhost:3001/api/persons/bad_id
